### ISSUE TITLE
support FIFO q?

### ISSUE THREAD

**Issue by jhaoheng** [roribio/alpine-sqs#41]
Hi 
Does this awesome project support FIFO feature?
And How should I use it?

**Comment by etos** [comment]
docker-compose.yml
```
    sqs:
      image: roribio16/alpine-sqs:latest
      container_name: alpine-sqs
      ports:
        - "9324:9324"
        - "9325:9325"
      volumes:
        - ./config/elasticmq.conf:/opt/config/elasticmq.conf
      stdin_open: true
      tty: true
```

/config/elasticmq.conf
```
include classpath("application.conf")

node-address {
   protocol = http
   host = "*"
   port = 9324
   context-path = ""
}

rest-sqs {
   enabled = true
   bind-port = 9324
   bind-hostname = "0.0.0.0"
   // Possible values: relaxed, strict
   sqs-limits = strict
}

queues {
   default {
     defaultVisibilityTimeout = 10 seconds
     delay = 5 seconds
     fifo = true
     contentBasedDeduplication = false
     receiveMessageWait = 0 seconds
   }
}
```
